# Copyright SecureKey Technologies Inc.
#
# SPDX-License-Identifier: Apache-2.0

swagger: "2.0"
info:
  title: Confidential Storage Hub
  description: Confidential Storage Hub
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /test:
    get:
      responses:
        200:
          description: test
definitions:
  Profile:
    type: object
    properties:
      id:
        type: string
      controller:
        type: string
      zcap:
        type: string
  ComparisonRequest:
    type: object
    properties:
      op:
        $ref: "#/definitions/Operator"
  Comparison:
    description: TODO - "comparison" does not sound apt as a name
    type: object
    properties:
      result:
        type: boolean
  Operator:
    type: object
    required:
      - type
    discriminator: type
    properties:
      type:
        type: string
  EqOp:
    allOf:
      - $ref: "#/definitions/Operator"
      - type: object
        required:
          - args
        properties:
          args:
            type: array
            items:
              $ref: "#/definitions/Query"
            minItems: 2
  Query:
    type: object
    required:
      - type
    discriminator: type
    properties:
      id:
        type: string
      type:
        type: string
  DocQuery:
    allOf:
      - $ref: "#/definitions/Query"
      - type: object
        required:
          - vaultID
          - docID
          - upstreamAuth
        properties:
          vaultID:
            type: string
          docID:
            type: string
          path:
            type: string
          upstreamAuth:
            type: object
            required:
              - edv
              - kms
            properties:
              edv:
                $ref: "#/definitions/UpstreamAuthorization"
              kms:
                $ref: "#/definitions/UpstreamAuthorization"
  RefQuery:
    allOf:
      - $ref: "#/definitions/Query"
      - type: object
        required:
          - ref
        properties:
          ref:
            type: string
  Authorization:
    type: object
    required:
      - requestingParty
      - scope
    properties:
      id:
        type: string
      requestingParty:
        type: string
      scope:
        type: object
        required:
          - resource
          - action
        properties:
          resourceID:
            type: string
          resourceType:
            type: string
          action:
            type: array
            items:
              type: string
              enum:
                - read
                - reference
          caveats:
            type: array
            items:
              $ref: "#/definitions/Caveat"
      zcap:
        type: object
  UpstreamAuthorization:
    type: object
    properties:
      baseURL:
        type: string
      zcap:
        type: string
  Caveat:
    type: object
    properties:
      type:
        type: string
        enum:
          - expiry
  ExpiryCaveat:
    allOf:
      - $ref: "#/definitions/Caveat"
      - type: object
        properties:
          duration:
            type: integer
            description: Duration (in seconds) for which this authorization will remain valid.
  Error:
    type: object
    properties:
      errMessage:
        type: string
